query(
  $currentProjectid:String!
  ) {
  currentProject(id:  $currentProjectid)
  {
    id
    kennung
    name
    lvs(orderBy:[{column:"kennung", order:ASC}]){
      id
      kennung
      name
    }
  }
}